// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: helloworld.proto

package go_mirco_api_hellworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Hellworld service

type HellworldService interface {
	Callme(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Take(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type hellworldService struct {
	c    client.Client
	name string
}

func NewHellworldService(name string, c client.Client) HellworldService {
	return &hellworldService{
		c:    c,
		name: name,
	}
}

func (c *hellworldService) Callme(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Hellworld.Callme", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hellworldService) Take(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Hellworld.Take", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hellworld service

type HellworldHandler interface {
	Callme(context.Context, *Request, *Response) error
	Take(context.Context, *Request, *Response) error
}

func RegisterHellworldHandler(s server.Server, hdlr HellworldHandler, opts ...server.HandlerOption) error {
	type hellworld interface {
		Callme(ctx context.Context, in *Request, out *Response) error
		Take(ctx context.Context, in *Request, out *Response) error
	}
	type Hellworld struct {
		hellworld
	}
	h := &hellworldHandler{hdlr}
	return s.Handle(s.NewHandler(&Hellworld{h}, opts...))
}

type hellworldHandler struct {
	HellworldHandler
}

func (h *hellworldHandler) Callme(ctx context.Context, in *Request, out *Response) error {
	return h.HellworldHandler.Callme(ctx, in, out)
}

func (h *hellworldHandler) Take(ctx context.Context, in *Request, out *Response) error {
	return h.HellworldHandler.Take(ctx, in, out)
}
